name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 18.182.222.102
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www
          git pull origin main
